services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: euvox
      POSTGRES_PASSWORD: euvox
      POSTGRES_DB: euvox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: euvox
      RABBITMQ_DEFAULT_PASS: euvox
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: euvox
      MINIO_ROOT_PASSWORD: euvoxsecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
