from euvox.operation_registry.base import RenderContext, RenderResult


class NumericPatchV1:
    type_name = "numeric_patch"
    schema_version = "v1"

    def validate(self, spec: dict[str, object]) -> list[str]:
        errors: list[str] = []
        if "target" not in spec:
            errors.append("missing required field: target")
        if "value" not in spec:
            errors.append("missing required field: value")
        value = spec.get("value")
        if value is not None and not isinstance(value, (int, float)):
            errors.append(f"value must be numeric, got {type(value).__name__}")
        bounds = spec.get("bounds")
        if bounds is not None:
            if not isinstance(bounds, list) or len(bounds) != 2:
                errors.append("bounds must be a two-element list [min, max]")
            elif isinstance(value, (int, float)):
                lo, hi = bounds[0], bounds[1]
                if not lo <= value <= hi:
                    errors.append(f"value {value} is outside bounds [{lo}, {hi}]")
        return errors

    def render(self, spec: dict[str, object], context: RenderContext) -> RenderResult:
        target = spec["target"]
        value = spec["value"]
        content = (
            f"# Generated by euvox optimizer\n"
            f"# Operation: {self.type_name}@{self.schema_version}\n"
            f"# ModVersion: {context.mod_version_id}\n"
            f"\n"
            f"@{target} = {value}\n"
        )
        file_path = f"common/scripted_values/euvox_{target}.txt"
        return RenderResult(
            files={file_path: content},
            description=f"Set {target} = {value}",
        )

    def complexity(self, spec: dict[str, object]) -> float:
        return 0.1

    def describe(self, spec: dict[str, object]) -> str:
        return f"Set {spec.get('target')} to {spec.get('value')}"
